# Generated by Django 3.1.2 on 2020-11-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201117_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('rootname', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('rootpassword', models.IntegerField()),
            ],
            options={
                'db_table': 'root',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('userphone', models.IntegerField()),
                ('password', models.IntegerField()),
                ('userid', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PollsStudentinfo',
        ),
    ]
