from  django.urls import path
from . import views

#app_name='polls'


urlpatterns = [                              #路由表
    path('Homepage/', views.Homepage),      #通过路由调用定义的方法此为主界面
    path('purchaser/', views.purchaser),
    path('register/', views.register_view),
    path('login/', views.login),
    path('Topurchaser/', views.Topurchaser),
    path('getagencys/' ,views.get_agency),
    path('',views.toLogin_view ),
    path('SearchAgency/',views.SearchAgency),
    path('Search_Agency/',views.Search_Agency),
    path('SearchMedicine/',views.SearchMedicine),
    path('Search_Medicine/',views.Search_Medicine),
    path('SearchClient/',views.SearchClient),
    path('Search_Client/',views.Search_Client),
    path('about/',views.about),
    path('ToMedicine/',views.ToMedicine),
    path('MedicineSearch/',views.MedicineSearch),
    path('MedicineSearch1/',views.MedicineSearch1),
    path('ToAgencys/', views.ToAgencys),
    path('ToClinet/', views.ToClinet),
    path('ClinetSearch/', views.ClinetSearch),
    path('SetAgency/', views.SetAgency),
    path('Setagency/', views.Setagency),
    path('SetClient/', views.SetClient),
    path('Setclient/', views.Setclient),
    path('SetClient1/', views.SetClient1),
    path('Setclient1/', views.Setclient1),
    path('SetMedicine/', views.SetMedicine),
    path('Setmedicine/', views.Setmedicine),
    path('SetMedicine1/', views.SetMedicine1),
    path('Setmedicine1/', views.Setmedicine1),
    path('PolishAgency/', views.PolishAgency),
    path('Get_PolishAgency/', views.get_Agency),
    path('Polishagency/',views.Polishagency),
    path('PolishMedicine/', views.PolishMedicine),
    path('Get_PolishMedicine/', views.get_Medicine),
    path('Polishmedicine/',views.Polishmedicine),
    path('PolishMedicine1/', views.PolishMedicine1),
    path('Get_PolishMedicine1/', views.get_Medicine1),
    path('Polishmedicine1/',views.Polishmedicine1),
    path('PolishClient/', views.PolishClient),
    path('Get_PolishClient/', views.get_Client),
    path('Polishclient/', views.Polishclient),
    path('PolishClient1/', views.PolishClient1),
    path('Get_PolishClient1/', views.get_Client1),
    path('Polishclient1/', views.Polishclient1),
    path('DeleteAgency/',views.DeleteAgency),
    path('Deleteagency/', views.Deleteagency),
    path('Get_DeleteAgency/', views.get_DeleteAgency),
    path('DeleteMedicine/', views.DeleteMedicine),
    path('Deletemedicine/', views.Deletemedicine),
    path('Get_DeleteMedicine1/', views.get_DeleteMedicine1),
    path('DeleteMedicine1/', views.DeleteMedicine1),
    path('Deletemedicine1/', views.Deletemedicine1),
    path('Get_DeleteMedicine/', views.get_DeleteMedicine),
    path('DeleteClient/', views.DeleteClient),
    path('Deleteclient/', views.Deleteclient),
    path('Get_DeleteClient/', views.get_DeleteClient),
    path('DeleteClient1/', views.DeleteClient1),
    path('Deleteclient1/', views.Deleteclient1),
    path('Get_DeleteClient1/', views.get_DeleteClient1),
    path('AgencyPrint/', views.AgencyPrint),
    path('ClientPrint/', views.ClientPrint),
    path('MedicinePrint/', views.MedicinePrint),
    path('AgencyHomepage/', views.AgencyHomepage),
    path('PolishUser/', views.PolishUser),
    path('Polishuser/', views.Polishuser),
    path('Get_PolishUser/', views.get_User),
    path('DeleteUser/', views.DeleteUser),
    path('Deleteuser/', views.Deleteuser),
    path('Get_DeleteUser/', views.get_DeleteUser),
    path('SetUser/', views.SetUser),
    path('Setuser/', views.Setuser),
    # path('curd/',views.curd_view),
    # path('curd/delete/',views.curd_delete,name='cueddelete'),
    # path('curd/deleteall/',views.curd_delete_all,name='curddeleteall')
    # path('login/', views.login_views, name='login'),
    # path('register/', views.register_view, name='register'),
    # path('ShowInfo/', views.studentInfo_view, name='sudentInfo'),
    # path('score/', views.score_view, name='score'),
    # path('stuInfo/add/', views.IntoaddStuView, name='addpage'),
    # path('stdInfo/', views.addStuView, name='stunfo'),
]
